### ISSUE TITLE
Can't set port in config

### ISSUE THREAD

**Issue by pawelchcki** [Wikia/dropwizard-logstash-encoder#1]
```
Unrecognized field at: logging.appenders.[1].port
    Did you mean?:
      - host
      - logFormat
      - threshold
      - queueSize
      - includeMdc
        [5 more]
```

**Comment by nmonterroso** [comment]
Oops. Doesn't work when you forget the getter/setter.

**Comment by nmonterroso** [comment]
Fixed in https://github.com/Wikia/dropwizard-logstash-encoder/commit/7fcee7600ba9cefd63613e0fa614852f472c574e?w=1 and has been promoted as version `1.0.2`. Still waiting for this to sync to central, which is still showing [1.0.1](http://search.maven.org/#search%7Cga%7C1%7Ccom.wikia) as the latest.

**Comment by nmonterroso** [comment]
Looks like search.maven.org hasn't updated yet, but the `1.0.2` artifact can be fetched already.
